DarthFin/DarthFin/Controllers/EntriesController.cs
using DarthFin.Models;
using DarthFin.Services;
using Microsoft.AspNetCore.Mvc;

namespace DarthFin.Controllers
{
    public class EntriesController : Controller
    {
        private readonly IEntriesService _entriesService;

        public EntriesController(IEntriesService entriesService)
        {
            _entriesService = entriesService;
        }

        public async Task<IActionResult> IndexAsync()
        {
            var model = new EntriesSearchModel();
            if (model.DateFrom == DateTime.MinValue)
            {
                model.DateFrom = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1);
            }
            if (model.DateTill == DateTime.MinValue)
            {
                model.DateTill = model.DateFrom.AddMonths(1);
            }
            return View(model);
        }

        public async Task<IActionResult> SearchAsync(EntriesSearchModel model, CancellationToken cancellationToken)
        {
            var entries = await _entriesService.Search(model.DateFrom, model.DateTill, cancellationToken);
            var newModel = new EntriesListModel()
            {
                Entries = entries
            };
            return PartialView("_SearchResultPartial", newModel);
        }
    }
}

DarthFin/DarthFin/Controllers/FiltersController.cs
using DarthFin.Dto;
using DarthFin.Services;
using Microsoft.AspNetCore.Mvc;

namespace DarthFin.Controllers
{
    public class FiltersController : Controller
    {
        private readonly IEntriesService _entriesService;
        private readonly IFiltersService _filtersService;
        private readonly ICategoriesService _categoriesService;

        public FiltersController(IEntriesService entriesService,
            ICategoriesService categoriesService,
            IFiltersService filtersService)
        {
            _entriesService = entriesService;
            _categoriesService = categoriesService;
            _filtersService = filtersService;
        }

        [HttpGet]
        public async Task<IActionResult> NewFilterModal(int entryId)
        {
            var entry = await _entriesService.GetById(entryId);
            FilterDto model = new()
            {
                Correspondent = entry.Correspondent,
                Information = entry.Information
            };
            model.Categories = await _categoriesService.GetAllAsync();

            return PartialView("_NewFilterPartial", model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync(FilterDto model, CancellationToken cancellationToken)
        {
            await _filtersService.CreateFilterAsync(model, true, cancellationToken);
            return NoContent();
        }
    }
}

DarthFin/DarthFin/Views/Entries/Index.cshtml
@model EntriesSearchModel

<form id="searchForm"
      asp-action="Search" asp-controller="Entries"
      methdt="post">
    <div class="card p-1">
        <div class="row">
            <div class="col w-auto">
                <div class="input-group">
                    <span class="input-group-text">From</span>
                    <input asp-for="DateFrom" class="form-control" />
                    <span class="input-group-text">Till</span>
                    <input asp-for="DateTill" class="form-control" />
                </div>
            </div>
        </div>
        <div class="mx-auto">
            <button type="submit" class="btn btn-primary m-1 mb-0">Search</button>
        </div>
    </div>
</form>

<div id="searchResult"></div>

@section Scripts {
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const form = document.getElementById("searchForm");
            const result = document.getElementById("searchResult");

            if (!form) return;

            form.addEventListener("submit", async function (e) {
                e.preventDefault();

                const response = await fetch(form.action, {
                    method: "POST",
                    body: new FormData(form),
                    headers: {
                        "X-Requested-With": "XMLHttpRequest"
                    }
                });

                result.innerHTML = await response.text();
            });
        });
    </script>
    <script>
        //Scripts for partial
        $(document).on("click", ".btn-new-filter", function(){
            var id = $(this).data("id");

            $.ajax({
                url: '@Url.Action("NewFilterModal", "Filters")',
                type: 'GET',
                data: {entryId: id},
                success: function(result){
                    $("#modalBody").html(result);

                    // show modal
                    var modal = new bootstrap.Modal(document.getElementById('filterModal'));
                    modal.show();
                },
                error: function(){
                    console.log("err");
                }
            });
        });

        $(document).on("click", "#btn-new-filter-save", function(){
            console.log('save');
            const form = document.getElementById("form-filter");
            if (!form) return;

            console.log(new FormData(form));

            // const response = await fetch('@Url.Action("Create", "Filters")', {
            //         method: "POST",
            //         body: new FormData(form),
            //         headers: {
            //             "X-Requested-With": "XMLHttpRequest"
            //         }
            //     });

            // var modal = new bootstrap.Modal(document.getElementById('filterModal'));
            // console.log(modal);
            // modal.hide();

             $.ajax({
                url: '@Url.Action("Create", "Filters")',
                type: 'POST',
                data: new FormData(form),
                processData: false,
                contentType: false,
                success: function(result){
                    console.log('success');
                    // close modal
                    bootstrap.Modal.getOrCreateInstance(
                        document.getElementById('filterModal')
                    ).hide();
                },
                error: function(){
                    console.log("err");
                }
            });
        });
    </script>
}

DarthFin/DarthFin/Views/Entries/_SearchResultPartial.cshtml
@model EntriesListModel

<form id="entriesForm">
    <table class="table-hover">
        <tr>
            <th>Date</th>
            <th>Receiver</th>
            <th>Comment</th>
            <th>Category</th>
            <th>Amount</th>
        </tr>
        @foreach (var entry in Model.Entries)
        {
            <tr>
                <td class="border">@((entry.RealDate ?? entry.EntryDate).Value.ToShortDateString())</td>
                <td class="border">@entry.Correspondent</td>
                <td class="border">@entry.Information</td>
                @if (entry.CategoryId.HasValue)
                {
                    <td class="border">@entry?.Category?.Name</td>
                }
                else
                {
                    <td class="border">
                        <button type="button"
                                class="btn btn-info btn-new-filter"
                        @*   data-bs-toggle="modal"
                            data-bs-target="#filterModal" *@
                                data-id="@entry.Id">
                            New filter
                        </button>
                    </td>
                }

                <td class="border">@entry.Amount</td>
            </tr>
        }

    </table>
</form>

<div class="modal fade" id="filterModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">New Filter</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>


            <div class="modal-body" id="modalBody">
                <!-- modal content -->
                Filter form goes here
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                    Close
                </button>
                <button id="btn-new-filter-save" type="button" class="btn btn-primary">
                    Save
                </button>
            </div>
        </div>
    </div>
</div>